# Generated by Django 3.2.5 on 2021-07-31 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
