# Generated by Django 3.2.5 on 2021-07-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_alter_post_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(choices=[('p10', 'post 10'), ('p11', 'post 11')], max_length=20),
        ),
    ]
