# Generated by Django 3.2.5 on 2021-07-31 21:16

import Blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_alter_post_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=Blog.models.timenow, help_text='تاریخ الان'),
        ),
    ]
